### ISSUE TITLE
duplicate switch condition cases in qss.js

### ISSUE THREAD

**Issue by dfkaye** [tomhodgins/qss#1]
Amazing work you've done here (and other repos - my jaw won't stay off the floor).

I was scanning the source for qss.js and came across the `switch (condition)` block where `case 'condition'` is tested twice - however, the second is *unreachable* due to the preceding `break` statements.

Anyway, that's here: https://github.com/tomhodgins/qss/blob/master/qss.js#L440-L450

Happy Thanksgiving.

**Comment by tomhodgins** [comment]
Thanks @dfkaye! It definitely was a bug, but what I hadn't implemented properly was the `yscroll` keyword, so I've now also made a better demo page where we can test all of these:

https://codepen.io/tomhodgins/pen/oodpMR

I've pushed the fix to the repo now so you should be able to play around with the fixed version now :D
Hope you have a wonderful Thanksgiving!

**Comment by dfkaye** [comment]
@tomhodgins that was fast.

QSS looks so promising I haven't been this enthused by code or snippet of any kind since maybe the owl selector popularized by Heydon Pickering a couple years back.

**Comment by tomhodgins** [comment]
Thank you so much, I think that's the best feedback I've ever gotten :3 Hope you enjoy having fun with this!
